name: Main workflow

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: PlanetXamarinFeed
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './output'
  DOTNET_VERSION: '3.1.x'
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup dotnet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build'
      run: |
        dotnet build --configuration Release

    - name: '.NET Publish'
      run: |
        dotnet publish --configuration Release -o ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}